#:schema node_modules/wrangler/config-schema.json
name = "bento"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]

route = { pattern = "bento.dispatcherpersada.workers.dev", custom_domain = true }

[vars]
BENTO_USERNAME = 'nowe-design'
