#:schema node_modules/wrangler/config-schema.json tes
name = "bento"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-07-13"

route = { pattern = "bento.dispatcherpersada.workers.dev", custom_domain = true }

[vars]
BENTO_USERNAME = 'nowe-design'
